import {Link} from "react-router-dom";
import {useDispatch,useSelector} from "react-redux";
import {removeHistory,clearHistory} from "./redux/store";
import {useTranslation} from "react-i18next";
import SEO from "./components/SEO";
import Calculator from "./components/Calculator";
import {fmt,fromSqft,SQFT_PER_DECIMAL,SQFT_PER_KATHA,SQFT_PER_BIGHA,SQFT_PER_ACRE} from "./utils/land";
import {useState} from "react";

export function Home(){const {t}=useTranslation();return <><SEO title="Bhumi Map | Bangladesh Land Measurement Calculator" description={t("heroText")}/><div className="hero bg-base-100 py-16"><div className="hero-content text-center"><div className="max-w-3xl"><div className="badge badge-primary mb-4">Bangladesh • বাংলা + English</div><h1 className="text-4xl md:text-6xl font-black">{t("heroTitle")}</h1><p className="py-6 text-lg opacity-80">{t("heroText")}</p><div className="flex flex-wrap gap-3 justify-center"><Link to="/calculator" className="btn btn-primary">{t("start")}</Link><Link to="/units" className="btn btn-outline">{t("explore")}</Link></div></div></div></div><div className="container mx-auto px-4 py-12"><Calculator/></div></>}

export function CalculatorPage(){const {t}=useTranslation();return <div className="container mx-auto px-4 py-10"><SEO title="Land Calculator Bangladesh | Bhumi Map" description={t("heroText")}/><h1 className="text-3xl font-black mb-6">{t("calculator")}</h1><Calculator/></div>}

export function Converter(){const {t}=useTranslation();const [unit,setUnit]=useState("decimal"),[value,setValue]=useState("");const map={sqft:1,decimal:SQFT_PER_DECIMAL,katha:SQFT_PER_KATHA,bigha:SQFT_PER_BIGHA,acre:SQFT_PER_ACRE};const sqft=(Number(value)||0)*map[unit];const r=fromSqft(sqft);const opts=[["sqft",t("sqft")],["decimal",t("decimal")],["katha",t("katha")],["bigha",t("bigha")],["acre",t("acre")]];return <div className="container mx-auto px-4 py-10"><SEO title="Katha to Decimal Converter | Bangladesh" description="Convert Katha, Decimal, Bigha, Acre and Square Feet in Bangladesh."/><div className="max-w-3xl mx-auto card bg-base-100 shadow-xl"><div className="card-body"><h1 className="text-3xl font-black">{t("converter")}</h1><div className="grid md:grid-cols-2 gap-4"><input className="input input-bordered" type="number" value={value} onChange={e=>setValue(e.target.value)} placeholder="Value"/><select className="select select-bordered" value={unit} onChange={e=>setUnit(e.target.value)}>{opts.map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></div>{value&&<div className="grid sm:grid-cols-2 gap-3 mt-5">{[[t("sqft"),r.sqft],[t("decimal"),r.decimal],[t("katha"),r.katha],[t("bigha"),r.bigha],[t("acre"),r.acre]].map(([k,v])=><div className="stat bg-base-200 rounded-box" key={k}><div className="stat-title">{k}</div><div className="stat-value text-2xl">{fmt(v,4)}</div></div>)}</div>}</div></div></div>}

export function Units(){const {t}=useTranslation();const rows=[[t("sqft"),"435.6 sq ft = 1 Decimal",""],[t("decimal"),"435.6 sq ft",""],[t("katha"),"720 sq ft",""],[t("bigha"),"20 Katha = 14,400 sq ft",""],[t("acre"),"43,560 sq ft = 100 Decimal",""],[t("hectare"),"≈ 2.471 Acres",""],[t("chhatak"),"45 sq ft",""],[t("gonda"),"864 sq ft",""],[t("kora"),"216 sq ft",""]];return <div className="container mx-auto px-4 py-10"><SEO title="Bangladesh Land Measurement Units | Bhumi Map" description="Bangladesh Katha, Decimal, Bigha, Acre and land measurement units explained."/><h1 className="text-3xl font-black mb-6">{t("unitsTitle")}</h1><div className="overflow-x-auto card bg-base-100 shadow"><table className="table"><thead><tr><th>Unit</th><th>Standard relationship</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td className="font-bold">{r[0]}</td><td>{r[1]}</td></tr>)}</tbody></table></div><div className="alert mt-6">{t("notice")}</div></div>}

export function Guide(){const {t}=useTranslation();return <div className="container mx-auto px-4 py-10 max-w-4xl"><SEO title="Bangladesh Land Measurement Guide | Bhumi Map" description="Learn how to calculate rectangle, square, triangle and irregular land in Bangladesh."/><h1 className="text-3xl font-black mb-8">{t("guideTitle")}</h1><div className="space-y-5"><div className="card bg-base-100 shadow p-6"><h2 className="text-xl font-bold">{t("rectangle")}</h2><p>Area = Length × Width.</p></div><div className="card bg-base-100 shadow p-6"><h2 className="text-xl font-bold">{t("triangle")}</h2><p>{t("triangleInfo")}</p></div><div className="card bg-base-100 shadow p-6"><h2 className="text-xl font-bold">{t("irregular")}</h2><p>{t("irregularInfo")}</p></div></div></div>}

export function History(){const {t}=useTranslation();const history=useSelector(s=>s.history),dispatch=useDispatch();return <div className="container mx-auto px-4 py-10"><SEO title="Land Calculation History | Bhumi Map" description="Saved land measurement calculations."/><div className="flex justify-between items-center mb-6"><h1 className="text-3xl font-black">{t("historyTitle")}</h1>{history.length>0&&<button className="btn btn-error btn-outline" onClick={()=>dispatch(clearHistory())}>{t("clear")}</button>}</div>{!history.length?<div className="alert">{t("noHistory")}</div>:<div className="space-y-3">{history.map(x=><div key={x.id} className="card bg-base-100 shadow"><div className="card-body flex-row items-center justify-between"><div><div className="font-bold capitalize">{x.shape}</div><div className="text-sm opacity-70">{new Date(x.date).toLocaleString()}</div><div>{fmt(x.result.sqft)} sq ft • {fmt(x.result.decimal,4)} Decimal • {fmt(x.result.katha,4)} Katha</div></div><button className="btn btn-sm btn-error btn-outline" onClick={()=>dispatch(removeHistory(x.id))}>{t("clear")}</button></div></div>)}</div>}</div>}

export function FAQ(){const {t}=useTranslation();return <div className="container mx-auto px-4 py-10 max-w-4xl"><SEO title="FAQ | Bangladesh Land Calculator" description="Frequently asked questions about Bangladesh land measurement."/><h1 className="text-3xl font-black mb-6">{t("faqTitle")}</h1><div className="join join-vertical w-full">{[["How many square feet is 1 Katha?","1 Katha is commonly standardized as 720 square feet."],["How many Decimal is 1 Acre?","1 Acre equals 100 Decimal."],["How is triangle land calculated?","Use ½ × base × perpendicular height, or Heron's formula when all three sides are known."],["Can I use this for legal land registration?","No. It is a calculation aid; verify legal measurements with official records and a qualified surveyor."]].map(([q,a])=><div className="collapse collapse-arrow join-item border border-base-300 bg-base-100" key={q}><input type="checkbox"/><div className="collapse-title font-semibold">{q}</div><div className="collapse-content"><p>{a}</p></div></div>)}</div></div>}

export function About(){const {t}=useTranslation();return <div className="container mx-auto px-4 py-10 max-w-3xl"><SEO title="About Bhumi Map" description="About Bhumi Map Bangladesh land measurement calculator."/><h1 className="text-3xl font-black mb-4">{t("aboutTitle")}</h1><p className="text-lg opacity-80">{t("heroText")}</p><div className="alert mt-8">{t("notice")}</div></div>}